// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: internal/proto/types.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FDRequest struct {
	state            protoimpl.MessageState   `protogen:"open.v1"`
	Method           string                   `protobuf:"bytes,1,opt,name=Method,proto3" json:"Method,omitempty"`
	Header           map[string]*HeaderFields `protobuf:"bytes,2,rep,name=Header,proto3" json:"Header,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body             []byte                   `protobuf:"bytes,3,opt,name=Body,proto3" json:"Body,omitempty"`
	ContentLength    int64                    `protobuf:"varint,4,opt,name=ContentLength,proto3" json:"ContentLength,omitempty"`
	TransferEncoding *StringSlice             `protobuf:"bytes,5,opt,name=TransferEncoding,proto3" json:"TransferEncoding,omitempty"`
	Host             string                   `protobuf:"bytes,6,opt,name=Host,proto3" json:"Host,omitempty"`
	RemoteAddr       string                   `protobuf:"bytes,7,opt,name=RemoteAddr,proto3" json:"RemoteAddr,omitempty"`
	RequestURI       string                   `protobuf:"bytes,8,opt,name=RequestURI,proto3" json:"RequestURI,omitempty"`
	Pattern          string                   `protobuf:"bytes,9,opt,name=Pattern,proto3" json:"Pattern,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FDRequest) Reset() {
	*x = FDRequest{}
	mi := &file_internal_proto_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FDRequest) ProtoMessage() {}

func (x *FDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FDRequest.ProtoReflect.Descriptor instead.
func (*FDRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_types_proto_rawDescGZIP(), []int{0}
}

func (x *FDRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *FDRequest) GetHeader() map[string]*HeaderFields {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *FDRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *FDRequest) GetContentLength() int64 {
	if x != nil {
		return x.ContentLength
	}
	return 0
}

func (x *FDRequest) GetTransferEncoding() *StringSlice {
	if x != nil {
		return x.TransferEncoding
	}
	return nil
}

func (x *FDRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *FDRequest) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *FDRequest) GetRequestURI() string {
	if x != nil {
		return x.RequestURI
	}
	return ""
}

func (x *FDRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

type FDResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Body          []byte                   `protobuf:"bytes,1,opt,name=Body,proto3" json:"Body,omitempty"`
	StatusCode    int32                    `protobuf:"varint,2,opt,name=StatusCode,proto3" json:"StatusCode,omitempty"`
	Length        int32                    `protobuf:"varint,3,opt,name=Length,proto3" json:"Length,omitempty"`
	Header        map[string]*HeaderFields `protobuf:"bytes,4,rep,name=Header,proto3" json:"Header,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FDResponse) Reset() {
	*x = FDResponse{}
	mi := &file_internal_proto_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FDResponse) ProtoMessage() {}

func (x *FDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FDResponse.ProtoReflect.Descriptor instead.
func (*FDResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_types_proto_rawDescGZIP(), []int{1}
}

func (x *FDResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *FDResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *FDResponse) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *FDResponse) GetHeader() map[string]*HeaderFields {
	if x != nil {
		return x.Header
	}
	return nil
}

type HeaderFields struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []string               `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeaderFields) Reset() {
	*x = HeaderFields{}
	mi := &file_internal_proto_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderFields) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderFields) ProtoMessage() {}

func (x *HeaderFields) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderFields.ProtoReflect.Descriptor instead.
func (*HeaderFields) Descriptor() ([]byte, []int) {
	return file_internal_proto_types_proto_rawDescGZIP(), []int{2}
}

func (x *HeaderFields) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type StringSlice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []string               `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringSlice) Reset() {
	*x = StringSlice{}
	mi := &file_internal_proto_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringSlice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringSlice) ProtoMessage() {}

func (x *StringSlice) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringSlice.ProtoReflect.Descriptor instead.
func (*StringSlice) Descriptor() ([]byte, []int) {
	return file_internal_proto_types_proto_rawDescGZIP(), []int{3}
}

func (x *StringSlice) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

var File_internal_proto_types_proto protoreflect.FileDescriptor

const file_internal_proto_types_proto_rawDesc = "" +
	"\n" +
	"\x1ainternal/proto/types.proto\x12\x05proto\"\x91\x03\n" +
	"\tFDRequest\x12\x16\n" +
	"\x06Method\x18\x01 \x01(\tR\x06Method\x124\n" +
	"\x06Header\x18\x02 \x03(\v2\x1c.proto.FDRequest.HeaderEntryR\x06Header\x12\x12\n" +
	"\x04Body\x18\x03 \x01(\fR\x04Body\x12$\n" +
	"\rContentLength\x18\x04 \x01(\x03R\rContentLength\x12>\n" +
	"\x10TransferEncoding\x18\x05 \x01(\v2\x12.proto.StringSliceR\x10TransferEncoding\x12\x12\n" +
	"\x04Host\x18\x06 \x01(\tR\x04Host\x12\x1e\n" +
	"\n" +
	"RemoteAddr\x18\a \x01(\tR\n" +
	"RemoteAddr\x12\x1e\n" +
	"\n" +
	"RequestURI\x18\b \x01(\tR\n" +
	"RequestURI\x12\x18\n" +
	"\aPattern\x18\t \x01(\tR\aPattern\x1aN\n" +
	"\vHeaderEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.proto.HeaderFieldsR\x05value:\x028\x01\"\xdf\x01\n" +
	"\n" +
	"FDResponse\x12\x12\n" +
	"\x04Body\x18\x01 \x01(\fR\x04Body\x12\x1e\n" +
	"\n" +
	"StatusCode\x18\x02 \x01(\x05R\n" +
	"StatusCode\x12\x16\n" +
	"\x06Length\x18\x03 \x01(\x05R\x06Length\x125\n" +
	"\x06Header\x18\x04 \x03(\v2\x1d.proto.FDResponse.HeaderEntryR\x06Header\x1aN\n" +
	"\vHeaderEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.proto.HeaderFieldsR\x05value:\x028\x01\"&\n" +
	"\fHeaderFields\x12\x16\n" +
	"\x06fields\x18\x01 \x03(\tR\x06fields\"%\n" +
	"\vStringSlice\x12\x16\n" +
	"\x06fields\x18\x01 \x03(\tR\x06fieldsB\x1fZ\x1d.com/ASparkOfFire/ignis/protob\x06proto3"

var (
	file_internal_proto_types_proto_rawDescOnce sync.Once
	file_internal_proto_types_proto_rawDescData []byte
)

func file_internal_proto_types_proto_rawDescGZIP() []byte {
	file_internal_proto_types_proto_rawDescOnce.Do(func() {
		file_internal_proto_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_types_proto_rawDesc), len(file_internal_proto_types_proto_rawDesc)))
	})
	return file_internal_proto_types_proto_rawDescData
}

var file_internal_proto_types_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_proto_types_proto_goTypes = []any{
	(*FDRequest)(nil),    // 0: proto.FDRequest
	(*FDResponse)(nil),   // 1: proto.FDResponse
	(*HeaderFields)(nil), // 2: proto.HeaderFields
	(*StringSlice)(nil),  // 3: proto.StringSlice
	nil,                  // 4: proto.FDRequest.HeaderEntry
	nil,                  // 5: proto.FDResponse.HeaderEntry
}
var file_internal_proto_types_proto_depIdxs = []int32{
	4, // 0: proto.FDRequest.Header:type_name -> proto.FDRequest.HeaderEntry
	3, // 1: proto.FDRequest.TransferEncoding:type_name -> proto.StringSlice
	5, // 2: proto.FDResponse.Header:type_name -> proto.FDResponse.HeaderEntry
	2, // 3: proto.FDRequest.HeaderEntry.value:type_name -> proto.HeaderFields
	2, // 4: proto.FDResponse.HeaderEntry.value:type_name -> proto.HeaderFields
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_internal_proto_types_proto_init() }
func file_internal_proto_types_proto_init() {
	if File_internal_proto_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_types_proto_rawDesc), len(file_internal_proto_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_types_proto_goTypes,
		DependencyIndexes: file_internal_proto_types_proto_depIdxs,
		MessageInfos:      file_internal_proto_types_proto_msgTypes,
	}.Build()
	File_internal_proto_types_proto = out.File
	file_internal_proto_types_proto_goTypes = nil
	file_internal_proto_types_proto_depIdxs = nil
}
