// Code generated by "stringer --type RuntimeEngine"; DO NOT EDIT.

package runtime

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RuntimeEngineGo-0]
	_ = x[RuntimeEngineJS-1]
}

const _RuntimeEngine_name = "RuntimeEngineGoRuntimeEngineJS"

var _RuntimeEngine_index = [...]uint8{0, 15, 30}

func (i RuntimeEngine) String() string {
	if i < 0 || i >= RuntimeEngine(len(_RuntimeEngine_index)-1) {
		return "RuntimeEngine(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RuntimeEngine_name[_RuntimeEngine_index[i]:_RuntimeEngine_index[i+1]]
}
